name: Crawl

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - run: pip install requests bs4
    - name: Run crawler
      run: python crawler/main.py
    - name: Add and commit
      id: add_commit
      uses: EndBug/add-and-commit@v9
      with:
        committer_name: Automated
        committer_email: actions@users.noreply.github.com
        message: "Latest data"
